[app]
id = "navigation_group"
[apps.basic]
use = "skaldos/sway/navigation_basic"
[compositions.active_members]
use = "skaldos/sway/active_members"
[compositions.ipc]
use = "skaldos/sway/ipc"
[functions.left]
[functions.right]
[functions.up]
[functions.down]
