[app]
id = "navigation_group"

[compositions.windows_list_nav]
use = "skaldos/sway/windows_list_nav"

[compositions.active_members]
use = "skaldos/sway/active_members"

[functions.left]
[functions.right]
[functions.up]
[functions.down]
