[app]
id = "groups"
[compositions.groups]
use = "skaldos/sway/groups"
[functions.create]
export = "groups.create"
[functions.add]
export = "groups.add"
[functions.remove]
export = "groups.remove"
[functions.clear]
export = "groups.clear"
[functions.show]
export = "groups.show"
[functions.list]
export = "groups.list"
[functions.memberships]
export = "groups.memberships"
[functions.select]
export = "groups.select"
[functions.deactivate]
export = "groups.deactivate"
[functions.current]
export = "groups.current"
