[composition]
id = "theme_ipc"

[compositions.ipc]
use = "skaldos/sway/ipc"

[functions.set_focused]
description = "Set the complete focused client color class."
[functions.set_focused_inactive]
description = "Set the complete focused-inactive client color class."
[functions.set_focused_tab_title]
description = "Set the complete focused tab-title color class."
[functions.set_unfocused]
description = "Set the complete unfocused client color class."
[functions.set_urgent]
description = "Set the complete urgent client color class."
[functions.set_background_file]
description = "Set one global image background with mode and fallback color."
[functions.set_background_color]
description = "Set one global solid-color background."
