[composition]
id = "basic_nav"

[compositions.ipc]
use = "skaldos/sway/core/ipc"

[functions.left]
description = "Move focus one native Sway step to the left."

[functions.right]
description = "Move focus one native Sway step to the right."

[functions.up]
description = "Move focus one native Sway step up."

[functions.down]
description = "Move focus one native Sway step down."
