[app]
id = "nav"

[compositions.basic_nav]
use = "skaldos/sway/basic_nav"

[compositions.windows_list_nav]
use = "skaldos/sway/windows_list_nav"

[functions.left]
[functions.right]
[functions.up]
[functions.down]
