[launcher]
name = "skaldos-sway"
adapter = "python_cli"
application = "skaldos/sway/cli"
function = "main"

[[modules]]
id = "dix/state"
source = "../../../dix/state"
[[modules]]
id = "dix/cli"
source = "../../../dix/cli"
[[modules]]
id = "dix/roba"
source = "../../../dix/roba"
[[modules]]
id = "skaldos/sway"
source = "../../sway"
